[build]
  command = "pip install -r requirements.txt && python -m nltk.downloader stopwords punkt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9"

[[plugins]]
  package = "@netlify/plugin-functions-python"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/streamlit-info"
  to = "/.netlify/functions/streamlit_wrapper"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false